### ISSUE TITLE
Markdown version of Datacard template

### ISSUE THREAD

**Issue by drskd** [PAIR-code/datacardsplaybook#14]
Hi,

Thanks a lot for this repository, I think this initiative is very interesting and it is something that I look forward to integrating in my data science projects!

I read on the .docx datacard template that there were going to be a markdown version of the template on the github repository. I'm not sure if it has already been uploaded. If not, do you know when do you think you could share it? 
If it's not in your priorities I will create one based on the docx version, but it will probably be a lighter version based on my needs so I'm not sure if it will be PR worthy.

**Comment by andrewzaldivar** [comment]
Hello! 

We're grateful for your kind remarks. We're also very interested in seeing how you integrate our work into your projects. If you're open to it, then consider sharing your experiences with us.

As for the Markdown version of the Data Cards template, we do, in fact, have that available for download, which you can find [here](https://github.com/PAIR-code/datacardsplaybook/blob/main/templates/DataCardsExtendedTemplate.md). Admittedly, the Markdown template was a bit hidden. But thanks to you, we're now making some adjustments to the repo and website in order to make the template discoverable to others.

Having said that, we do acknowledge that the Markdown template is not exactly in parity with the .docx template. For example, the Markdown template does not contain instructions on how to fill in each of the sections. But it should be plenty for you to experiment with for now. 

We do have some open requests to not only achieve full parity, but also convert the template into other formats. We welcome any contributions on this.

For now, I'll close this issue — but should [the Markdown template](https://github.com/PAIR-code/datacardsplaybook/blob/main/templates/DataCardsExtendedTemplate.md) we have available is not sufficient for your needs, then reply back and we'll reopen this issue.
